eks-application-chart:
  deployments:
    - name: countries-service
      replicas: 0
      data: testing
      fallback:
        failure: 9
        failtes: test
      containers:
        - name: countries-test
          image:
            repository: docker-appimage
          resources: data_test
